## Libraries 
library(readr)
library(readxl)
library(dplyr)
library(plyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(stringr)
library(forcats)
library(tidyverse)
library(ggpubr)
library(ggridges)
library(factoextra)
library(patchwork)
library(jsonlite)
library(httr)
library(xlsx)
library(shiny)
library(irr) 
library(psych)
library(blandr) 
library(BlandAltmanLeh)
library(rstatix)
library(ggsignif)
library(extrafont)
pitt_colors= c("#003594", "#FFB81C","grey51","black","white")
